import React from "react";
import Signup from "./components/Auth/Signup/Signup";
import Head from "next/head";

const signup = () => {
  return (
    <>
      <Head>
        <title>signUp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Signup />;
    </>
  );
};

export default signup;
